# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"
  - "/template/"

# Site settings
title: O Antiphons
email: rmvwills@gmail.com
name: Rose Wills
description: >
  This is the home page for the O Antiphons traditionally prayed on the evenings of the week leading up to Christmas (Dec. 17-23). One verse per night is prayed/sung before and after the Magnificat during evening Vespers.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/o-antiphons" # the subpath of your site, e.g. /blog/
url: "http://rosewills.github.io" # the base hostname & protocol for your site
cover: "/assets/images/ornament-raw.png"
acover: ""	# /assets/art/windowsill.png
bcover: ""
logo:
future: false

# Build settings
markdown: kramdown
highlightjs_theme: "monokai-sublime"

# Pagination
pagination:											# Configuration for the Jekyll 3 Pagination Gem (the values here represent the defaults if nothing is set)
  enabled: true									# Site-wide kill switch, disabled here it doesn't run at all 
  debug: false									# Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  per_page: 5										# How many objects per paginated page, used to be `paginate` (default: 0, means all)
  limit: 0											# Limit how many pagenated pages to create (default: 0, means all)
  title: ':title - page :num'		# [optional] the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  sort_field: 'date'						# [optional] defines the field that the posts should be sorted on (omit to default to 'date')
  sort_reverse: true						# [optional] sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  tag: ''												# [optional] the default tag to use, omit to disable
  locale: '' 										# [optional] the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code)
  extension: html								# [optional] the default file extension for generated pages (e.g html, json, xml). Internally this is set to html by default.
  indexpage: 'index'						# [optional] the default name of the index file for generated pages (e.g. 'index.html') without file extension
  trail:												# [optional] controls how the pagination trail for the paginated pages look like. omit or set both before and after to zero to disable.
    before: 2
    after: 2
  permalink: '/page/:num/'			# The permalink structure for the paginated pages (this can be any level deep)
                                    # permalink: '/page/:num/'      # Pages are index.html inside this folder (default)
                                    # permalink: '/page/:num.html'  # Pages are simple html files
                                    # permalink: '/page/:num'       # Pages are html files, linked jekyll extensionless permalink style.
inter_post_navigation: false

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"


# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Listen to us on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Visit our Tumblr
    share: false

  - name: Twitter
    icon: twitter
    username:
    url:
    desc: Follow me on Twitter
    share: true

  - name: LinkedIn
    icon: linkedin
    username:
    url:
    desc: Connect with me on LinkedIn
    share: true

  - name: GitHub
    icon: github
    username: This website is powered by GitHub Pages.
    url: https://github.com/rosewills
    desc: This website is powered by GitHub Pages.
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: true


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
