
title: Rose Wills
url: 'https://rosewills.github.io'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Rose Wills  ## put your name
title: 'Writer and Science Communicator'  ## your title
location: Athens , GA


## Social Profiles
# facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com/rosevwills  ## your twitter account url
linkedin: http://www.linkedin.com/rmvwills  ## your linkedin account url
# dribbble: http://www.dribble.com  ## you dribbble account url
# foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
